Sprint #19 T.Z. Collector: Service for receiving data from hubs, enco…
ir0nmand0/plus-smart-home-tech pull request #1
Opened 2024-11-15 21:25 UTC by ir0nmand0

Приветствую, отказался от имплементации Serializer<SpecificRecordBase> в пользу kafka-avro-serializer, переработал код так, чтобы не было приведение типов, в этом помог паттерн Visitor. Ну и познакомился с MapStruct.
P.S. хотелось сгенерить по спецификации сущности при помощи openapi, но не стал, так как все таки это учебный проект.

2024-11-16 03:53 UTC, EugeneLenkevich commented
>  Ну и познакомился с MapStruct(особенно понравилось, когда понял, что его нужно в помнике указывать после Lombook).

Хохо, а бывает еще версии библиотек конфликтуют или пролазит сразу две разные версии одной библиотеки, в общем, бывает)

> P.S. хотелось сгенерить по спецификации сущности при помощи openapi, но не стал, так как все таки это учебный проект.

Вообще, проще всегда сгенерить, это же не долго, но ладно, на самом деле по разному бывает в реальных проектах

2024-11-16 05:05 UTC, EugeneLenkevich requested changes
Привет, Дмитрий! Спасибо за PR.

Ну что, как задание, выглядит страшно, однако сама идея простая. Но, очень много незнакомых, страшных слов и основная проблема как раз в том, чтобы разобраться в том как это все собрать вместе :)

Visitor - круто

Первое что хочется сделать - логирование. Допустим у нас система работает, принимает какие то данные, но появилось подозрение что какой то из датчиков не шлет данные, например. Мы можем по логу поискать сообщения по id тому же, но все данные нам не надо выводить, логи станут огромными, потому выводим необходимый минимум. А вот в режиме отладки можно выводить уже все.

Далее. Логика достаточно запутанная, тут бы было очень хорошо написать тесты. Один тест чисто на контроллер, то есть на сам контракт, сервис замокать с помощью Mockito. Мы такое делали с MockMvc. 
Второй тест - на сервис. Нам надо будет поднять контекст, замокать очередь, передать объект (в идеале всех типов, а совсем в идеале чтобы доступные варианты подтягивались автоматически, тогда у нас тест будет падать когда добавили новый объект, но не добавили методы в визитор) через сервис и убедиться что сообщение ушло в мок очереди 

![image](https://github.com/user-attachments/assets/9ab2af82-fc25-47a2-b21a-fc8237a87403)

![image](https://github.com/user-attachments/assets/f3b07516-69b3-4dc6-b03e-6aa69449427d)

https://habr.com/ru/articles/444982/

На тестах не настаиваю, но будет очень круто если получится их сделать. Все эти интеграции очень сложно вручную отлаживать, а если мы говорим о микросервисах то это может быть сущим кошмаром так как сервисов много, сообщений логов тьма и разобраться что куда и откуда та еще задача. Однако такой тест еще на этапе сборки отловит несоответствия, это будет проще и быстрее :)

2024-11-16 05:05 UTC, EugeneLenkevich commented on telemetry/collector/src/main/java/ru/yandex/practicum/controller/CollectorController.java
> +        log.debug("Received sensor event: {}", event);
Это то можно было руками не логировать, прикрутить тот же logback. Но это мелочи


https://www.baeldung.com/spring-logbook-http-logging

2024-11-16 05:05 UTC, EugeneLenkevich commented on telemetry/collector/src/main/java/ru/yandex/practicum/service/impl/EventProcessingServiceImpl.java
> +        event.accept(this); // Используем Visitor для событий датчиков
Часто еще применяют паттерн стратегия
У каждого события же есть тип, SensorEventType. Обработчики складываются в мапу, 
и далее по типу получаем нужный обработчик.

2024-11-16 05:05 UTC, EugeneLenkevich commented on telemetry/collector/src/main/java/ru/yandex/practicum/service/impl/EventProcessingServiceImpl.java
> +        log.debug("Processing ClimateSensorEvent: {}", event);
Скорее всего лог будет неинформативен, мы не будем на уровне info видеть какие сообщения ходят.
Предложу вот такую схему

log.info("Processing ClimateSensorEvent: {}", event.getId(), event.getHubId(), event.getTimestamp());
log.debug("ClimateSensorEvent= {}", event)

Так на уровне info мы будем видеть какие события с какими id приходят, а на уровне debug мы будем видеть содержимое самих событий, но в этом случае лог очень быстро будет расти и, потому, обычно в продакшене debug выключен и стоит info

2024-11-21 16:25 UTC, ir0nmand0 commented on telemetry/collector/src/main/java/ru/yandex/practicum/controller/CollectorController.java
> +        log.debug("Received sensor event: {}", event);
Увы автоматизировать не получилось из-за: 
- Несовместимость версий SLF4J между Spring Boot 3.x (использует SLF4J 2.x) и Apache Avro (зависит от SLF4J 1.7.x).
- Из-за этого возникают ошибки при загрузке класса "org.slf4j.impl.StaticLoggerBinder".

Решение:
- Исключить стандартный механизм логирования Spring Boot (spring-boot-starter-logging).
- Использовать SLF4J версии 1.7.x и добавить реализацию логгера slf4j-simple.
- Оставить современную версию Java (Java 21) для использования всех возможностей языка. 

Потратил уйму времени на попытку прикрутить, что только не пробовал, только как не исключал, бесполезно.

2024-11-21 16:25 UTC, ir0nmand0 commented on telemetry/collector/src/main/java/ru/yandex/practicum/service/impl/EventProcessingServiceImpl.java
> +        event.accept(this); // Используем Visitor для событий датчиков
Я так изначально и сделал, но никак в таком случае от приведения типа не избавиться, visitor идеально подошел для этой задачи. Плюс я выкинул getType заменив анотацией @JsonTypeName, так как считаю такой подход более правильным, ведь нам нужно это только для выбора правильного класса.

2024-11-21 16:25 UTC, ir0nmand0 commented on telemetry/collector/src/main/java/ru/yandex/practicum/service/impl/EventProcessingServiceImpl.java
> +        log.debug("Processing ClimateSensorEvent: {}", event);
исправил

2024-11-21 16:25 UTC, ir0nmand0 commented
> На тестах не настаиваю, но будет очень круто если получится их сделать. Все эти интеграции очень сложно вручную отлаживать, а если мы говорим о микросервисах то это может быть сущим кошмаром так как сервисов много, сообщений логов тьма и разобраться что куда и откуда та еще задача. Однако такой тест еще на этапе сборки отловит несоответствия, это будет проще и быстрее :)

Сделал, еще тот квест был конечно...

2024-11-21 17:14 UTC, EugeneLenkevich commented on telemetry/collector/src/main/java/ru/yandex/practicum/service/impl/EventProcessingServiceImpl.java
> +        event.accept(this); // Используем Visitor для событий датчиков
Ну в принципе да, все верно, получается так декларативненько, более чем наглядно.

2024-11-21 17:43 UTC, EugeneLenkevich commented
> Сделал, еще тот квест был конечно...

Ох, а я ведь волновался, оставил коммент только про логирование, но так и подумал что ты в итоге ушел писать тесты :D
Только смотри, ты сделал интеграционный тест на всю эту историю, начиная с контроллера. А еще можно было написать два теста, на каждый слой, один бы проверял сам контроллер, а другой бы проверял то, что, приняв на вход  в сервис определенное событие, в кафку (в мок очереди) уезжает соответствующий объект.
Плюс сами события, приходящие в контроллер, можно было хранить в текстовых файлах и десериализовать в тесте. Так мы бы еще форматы и десериализацию за одно проверяли.
Но это детали, в целом то же самое что и уже сделано, общий смысл тот же, просто немного по другому

Но, в целом, надеюсь было очень полезно, после написания таких тестов как минимум должно было стало гораздо понятней как спринг внутри работает и как можно, в тестовых целях, бины заменять на различные заглушки и моки :)

2024-11-21 17:45 UTC, EugeneLenkevich approved these changes
![Uploading image.png…]()

2024-11-21 18:21 UTC, ir0nmand0 commented
> Но, в целом, надеюсь было очень полезно, после написания таких тестов как минимум должно было стало гораздо понятней как спринг внутри работает и как можно, в тестовых целях, бины заменять на различные заглушки и моки :)

Все так, что касается десериализации я еще не дошел до следующего ТЗ, поэтому что там будет посмотрю, но благодаря мапперу не думаю, что будет сложно реализовать это.

Изолированные тесты не захотел, понимаю, что в какой-то степени они производительнее, но быстрее и правильнее я подумал сделал интеграционные, А вообще кафку в докере поднимать и проверять по настоящему было бы интереснее...

P.S. Java слишком не простая, чем дальше учусь, чем больше пишу различных решений (телеграм бота, интеграция с sftpgo), тем больше понимаю, что нифига не знаю...

2024-11-22 06:26 UTC, EugeneLenkevich commented
> Изолированные тесты не захотел, понимаю, что в какой-то степени они производительнее, но быстрее и правильнее я подумал сделал интеграционные, А вообще кафку в докере поднимать и проверять по настоящему было бы интереснее...
 
Ну в целом да, конкретно тут достаточно простого интеграционного теста.

К слову,  если в общем подойти к вопросу, то тут дело вот такое. Тесты по слоям убирают нам комбинаторную сложность. То есть когда мы хотим написать тест который охватывает все возможные варианты, то мы должны перебрать все варианты одного слоя и все варианты другого одновременно, и получаем декартово произведение вариантов. К тому же не все варианты физически получается проверить. Потому часто пишут множество мелких тестов и небольшое количество интеграционных, которые проверяют какие то основные сценарии, но не все, иначе трудозатраты на их написание улетают куда то в космос, плюс их еще и поддерживать надо. Можешь погуглить про пирамиду тестирования. А вообще написание хороших тестов - это целое искусство :)

> P.S. Java слишком не простая, чем дальше учусь, чем больше пишу различных решений (телеграм бота, интеграция с sftpgo), тем больше понимаю, что нифига не знаю...

Так и есть, это огромная платформа, ее всю охватить невозможно, надо на чем то конкретном специализроваться, иначе не получится

2024-11-22 11:46 UTC, merged